### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by hyunsYang** [linaro-swg/kmgk#26]
Hello,

I am opening this issue because I got some error as below (I compiled with Android v9, kmgk May 24, 21 version)

optee_keymaster.cpp
error: ‘NegotiateMessageVersion’ was not declared in this scope
  message_version_ = NegotiateMessageVersion(versionReq, versionRsp);
error: ‘GetVersion2Response’ does not name a type;
 GetVersion2Response OpteeKeymaster::GetVersion2(const GetVersion2Request& /* request */)

I guess it's because of "android_keymaster_messages.h"
Which Android version is minimum version?

**Comment by vchong** [comment]
Please try the `opt313_pie_20210428` instead of `master`.

**Comment by hyunsYang** [comment]
Thank you for your prompt response.
I try to compile the opt313_pie_20210428 instead of master.
It works well.

The opt313_pie_20210428 is thought to support the lower version of Android.
Will it be updated in two versions?

**Comment by vchong** [comment]
You're welcome.
Glad it works.

> The opt313_pie_20210428 is thought to support the lower version of Android.
Will it be updated in two versions?

The `opt313_pie_20210428` is the 'same' as the `master` branch with the exception of patches/changes reverted to make it compile on Pie. Does that answer your question?

**Comment by hyunsYang** [comment]
Yes, it does.  thank you.

I have one more question.
Do you have any plan to implement Keymaster 4.0 functionality or additional features?

**Comment by vchong** [comment]
You're welcome.

> Do you have any plan to implement Keymaster 4.0 functionality or additional features?

No. There are no further requests at the moment from our members so far for further functionalities or features in this area. Patches are always welcome. ; )

**Comment by hyunsYang** [comment]
Thank you for your information :)
 I'll close this issue.
