### ISSUE TITLE
TA_rsa_finish issue

### ISSUE THREAD

**Issue by ljmblueday** [linaro-swg/kmgk#28]
Hello,

When I use RSA sign and verification with this keymaster TA, I have some problems at TA_rsa_finish function.
When I just sign with some message and verify again using the output, the two values do not match.
If I modify the source code as follows, it will be verified correctly. Is there any problem with modifying the source like this?

```
index e9ac281d..c23b6945 100644
--- a/keymaster-ta/src/crypto_rsa.c
+++ b/keymaster-ta/src/crypto_rsa.c
@@ -320,9 +320,12 @@ keymaster_error_t TA_rsa_finish(keymaster_operation_t *operation,

                        output->data_length = *out_size;
                        *out_size = 0;
-                       if (TEE_MemCompare(output->data, input->data,
+                       if (TEE_MemCompare(output->data, input->data+1,
                                        output->data_length) != 0) {
                                EMSG("RSA no pad verification signature failed");
```

condition
algorithm: RSA 

padding: no padding

Test process
1) generate key(random)
2) signing
3) verification(with signing output)

Error message
[00009852.820365](KCPU1):E/TA:  TA_rsa_finish:328 RSA no pad verification signature failed
[00009852.820365](KCPU1):E/TA:  TA_finish:1860 Finish operation failed with error code ffffffe2

Best Regards,
Edward Lee

**Comment by vchong** [comment]
Hi Edward,

What are you using to test?
Are you able to run VtsHalKeymasterV3_0TargetTest? If yes, is the SigningOperationsTest.AesEcbSign test case failing?
Did you make any changes of your own?
What is your build environment and version?

**Comment by ljmblueday** [comment]
I am sorry, I just tested RSA algorithm (not AES algorithm) without ECB mode.

**Comment by vchong** [comment]
Sorry, I should have noticed the discrepancy as well. In any case, it doesn't change the questions, just the related VTS test.

What are you using to test?
Are you able to run `VtsHalKeymasterV3_0TargetTest`? If yes, is the `VerificationOperationsTest.RsaSuccess` test case failing? If it's failing as well and your patch fixes it then I can take your patch. Otherwise it might be an issue with you test code.
Did you make any changes of your own?
What is your build environment and version?

**Comment by ljmblueday** [comment]
I did not change this code. I just use message **0x00** 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x30 0x31 0x32.(32byte)
I test with VtsHalKeymasterV3_0TargetTest, I can pass this test. But If I change input message from original message to my own message 0x00 0x32 0x33 ......, I can see this error message.

**Comment by vchong** [comment]
Does the `VtsHalKeymasterV3_0TargetTest` test pass with the original message and your message with your patch?

**Comment by ljmblueday** [comment]
https://books.google.co.kr/books?id=xZDIAu90ukEC&pg=PA94&lpg=PA94&dq=nopadding+leading+zeros+disappear&source=bl&ots=lvZQRSm2t4&sig=ACfU3U287wZJpTdDaJuGZlHMLLiNsBPTkg&hl=en&sa=X&ved=2ahUKEwikkcOhiNH0AhXjh1YBHTMoAYcQ6AF6BAgZEAM#v=onepage&q&f=false

Please see this document. My test message is started with 0x00. (VTS test message "1234.... 12"(32byte))

After I changed the code as below, I can pass it.

`-                       if (TEE_MemCompare(output->data, input->data,`
`+                       size_t diff = input->data_length - output->data_length;`
`+                       if (TEE_MemCompare(output->data, input->data + diff,`

My test environment.
I use your CA and TA but I just use my own test application (not VTS)

**Comment by vchong** [comment]
Ok, thanks for the document. If I understand it correctly, you're using an input that requires padding, but you want to use the code flowing through the segment in `TA_rsa_finish()` that specifically states that it **is** for `KM_PAD_NONE`, i.e. no padding? If so, then the patch, or rather the hack, will then just break all valid messages that doesn't required padding. It also does **not** really make your test pass as you're not really comparing the output with the actual input, i.e. with the leading 0s. Rather,  you're comparing the output with the input that has the leading 0s stripped away. Maybe you should try setting the padding mode in your CA to something else like `RSA_PKCS1_1_5_SIGN` instead?

Are you using an aosp environment or just regular linux or something else altogether?

**Comment by ljmblueday** [comment]
Thanks for your advice. I use just regular Linux. The user does not know whether a message starting with 0x00 is converted to a big number and calculated, so it is assumed that all 32 bytes are compared.

**Comment by vchong** [comment]
You're welcome and sorry for the delay. So the TA is written specifically for the use of AOSP keystore which comes with tags to designate whether the message is padded or not. It is the same with the example in the book you referenced above. `PKCS1Padding` is used to designate padding is required. We can't just change it for any generic or specialized usage. Similarly, if you use it for another purpose other than what it's written for, then not sure if it'll work properly for you and you might have problems like what you're facing now.

> The user does not know whether a message starting with 0x00 is converted to a big number and calculated, so it is assumed that all 32 bytes are compared.
Ok, but your patch above is changing it to compare less than 32 bytes.

One more thing to check is when you generate key. You have to specify which padding modes may be used with the key. If not, I assume only no padding is supported which probably doesn't work with your message.

**Comment by ljmblueday** [comment]
Thanks for your comment. I understand your advice.
