### ISSUE TITLE
TEE_MACCompareFinal issue

### ISSUE THREAD

**Issue by vchong** [linaro-swg/kmgk#29]
Originally submitted by @ydonghyuk @ https://github.com/OP-TEE/optee_website/issues/136.

Hello,

I am verifying the sign/verify operation of HMAC (sha2_256) using OPTEE-based linaro-kmgk keymaster.
There is a confusion in the verification process, so I ask for your opinion.

More specifically, it is an operation method of the TEE_MACCompareFinal function.

- condition
 1/ algorithm: HMAC
 2/ digest: SHA2_256

- Test process
 1/ generate key (192bit)
 2/ sign (mac length: 160bit)
 3/ verify

- Result
 TEE_ERROR_MAC_INVALID

We confirmed that the test passed with the patch below.
However, we wonder why the truncated MAC is not being verified and what issue was there.

```
diff --git a/lib/libutee/tee_api_operations.c b/lib/libutee/tee_api_operations.c
index 4323e985..368fac56 100644
--- a/lib/libutee/tee_api_operations.c
+++ b/lib/libutee/tee_api_operations.c
@@ -1265,12 +1265,7 @@ TEE_Result TEE_MACCompareFinal(TEE_OperationHandle operation,
        if (res != TEE_SUCCESS)
                goto out;

-       if (computed_mac_size != macLen) {
-               res = TEE_ERROR_MAC_INVALID;
-               goto out;
-       }
-
-       if (consttime_memcmp(mac, computed_mac, computed_mac_size) != 0) {
+       if (consttime_memcmp(mac, computed_mac, macLen) != 0) {
                res = TEE_ERROR_MAC_INVALID;
                goto out;
        }
```

Thanks & Regards

**Comment by ydonghyuk** [comment]
If it has been reviewed, please give a brief comment first.

**Comment by vchong** [comment]
Sorry for the delay. So comparing the full MAC is the regular/normal use case designated by GP for the TEE Spec. Handling of truncated MAC in `optee_os` core requires proper updates to the specs first and so cannot be implemented at this point. The TA itself needs to handle this case for now. See https://github.com/OP-TEE/optee_os/issues/4725 for references and details, and https://github.com/OP-TEE/optee_os/blob/master/ta/pkcs11/src/processing_symm.c#L916-L937 for sample implementation.

**Comment by ydonghyuk** [comment]
Thanks for your answer.
Are there any spec updates planned for current issues?

**Comment by vchong** [comment]
You're welcome. We're not a GP member so we don't have access to those kinds of information, but if you look at https://github.com/OP-TEE/optee_os/pull/4735#issuecomment-876298090 which is dated Jul 8 of this year, it says "updates to the GP spec **should sufficient interest be shown**", which seems to indicate there are currently not enough interest to push this forward for now. 

If you or your company have/has any affiliation with GP, you can perhaps get in touch with the point of contact and provide some feedback or suggestion regarding this.

**Comment by ydonghyuk** [comment]
I understood your words.
Can I close this issue myself?

**Comment by vchong** [comment]
That's good. Thanks.
I think I've to close it since I opened it.
Ok to close?

**Comment by ydonghyuk** [comment]
Yes, I'm ok.
