### ISSUE TITLE
Anyplan for kmaster 4.0 or keymint?

### ISSUE THREAD

**Issue by lxxstone** [linaro-swg/kmgk#31]
Hi guys，
I would like to ask if there is any plan to continue this project 4.0 or 4.1 or Keymint？
thanks

**Comment by massonju** [comment]
Hi All,

Any update/plan of having keymint support ?
At Baylibre we will start to work on that, maybe we can join our force to achieve this task.
We will target keymint since keymaster is deprecated from Android 14.

Please let me know if you have some work/branch ongoing.

Thanks

**Comment by jockebech** [comment]
Hi, currently we (OP-TEE people, Linaro) have no ongoing work and no plans of updating this. So whoever interested in taking a lead here is more than welcome.

**Comment by massonju** [comment]
Okay thanks for the update @jbech-linaro

We will start working on the Keymint part, once we have something we will send PR :)
