### ISSUE TITLE
How/where to report a security vulnerability for this project?

### ISSUE THREAD

**Issue by bingzhux** [linaro-swg/kmgk#37]
I believe that I found some security vulnerabilities in this project repo. 

However it seems that I cannot find the entry to report that (and assign CVEs by github).

Typically, it should be here: https://github.com/linaro-swg/kmgk/security 
but it doesn't allow me to create a new one.

**Comment by jockebech** [comment]
Hi @bingzhux ,

I see it over here: https://github.com/linaro-swg/kmgk/security/advisories, up there in the right corner you have a green button saying "New draft security advisory".

A question thought not directly related to this, is that this git is no longer maintained. Beside getting a few pull requests, we haven't done anything to this git in a couple of years, i.e., it is subjected to bit rot. So I will probably discuss with the other OP-TEE maintainers whether it's time to deprecate this git if there is no one willing to take the maintainer role for it.

**Comment by bingzhux** [comment]
Thanks @jbech-linaro for your quick response!

It seems to me that it would be difficult to find maintainers for this project in a longer term, because I believe the trend will be moving to RUST based AOSP Keymint implementation for OP-TEE OS. 

For the button you mentioned **New draft security advisory**, I cannot see it there, probably because of permission control. 

See screenshot below.

![image](https://github.com/user-attachments/assets/76965f23-af72-4ff0-9fac-1e63fb50baa7)

**Comment by jockebech** [comment]
> It seems to me that it would be difficult to find maintainers for this project in a longer term, because I believe the trend will be moving to RUST based AOSP Keymint implementation for OP-TEE OS.
> 

Yes, I think you're right. That going with Rust is yet another challenge for this particular git. As mentioned, I will discuss this with the other OP-TEE maintainers. It's likely that we'll archive this git.

> For the button you mentioned **New draft security advisory**, I cannot see it there, probably because of permission control.

It should be there now, please try again.

**Comment by bingzhux** [comment]
Thank you, It works now. 

I need a few days or weeks to fix our own product before submitting the issue here.
