### ISSUE TITLE
Key size must be specified

### ISSUE THREAD

**Issue by moonhjh** [linaro-swg/kmgk#6]
when device boot, vold need keymaster create key,but keymaster TA print log"Key size must be specified", create key failed,device reboot。

I find keymaster CA has sended "key size" parameter to keymaster TA, its tag is 30000003,but when keymaster TA  call "TA_deserialize_param_set", the tag is 0, I dump params memory info in TA and CA, the memory info is same, i don't know the reson of this.

**Comment by vchong** [comment]
Is this on your own platform and port? Which aosp version? Any log files? Problems like this can be due to using 32- vs 64-bit variables.

**Comment by moonhjh** [comment]
this is on my own platform, aosp version is 9.0, I find the size of "SIZE_OF_ITEM(params->params)" is different in CA and TA, My TA and CA is compiled  separately，use different toolchains， CA compiles to use aosp toolchains，TA compiles to use “gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu”

**Comment by moonhjh** [comment]
In TA, I Modify SIZE_LENGTH to 4, and Modify SIZE_OF_ITEM(params->params) to 24, work well

**Comment by vchong** [comment]
Glad you got it worked out.
